# Generated by Django 4.2.25 on 2025-11-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0008_modelversion_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelversion",
            name="category",
            field=models.CharField(
                choices=[
                    ("sentiment", "Sentiment"),
                    ("recommendation", "Recommendation"),
                    ("text-classification", "Text Classification"),
                ],
                default="sentiment",
                max_length=50,
            ),
        ),
    ]
