# Generated by Django 4.2.25 on 2025-11-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note2webapp", "0009_alter_modelversion_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="bundle_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="model_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="predict_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="schema_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
